### ISSUE TITLE
Esoteric problem with nunjucks shortcode in Powershell 7

### ISSUE THREAD

**Issue by lwojcik** [NJAldwin/eleventy-plugin-gen-favicons#12]
Hi!

First of all, thank you very much for your work. This plugin rocks!

I use it across many projects of mine and I recently was contacted by someone who tried to run my Eleventy template using Windows 10. When I tried reproducing their issue on a Virtualbox machine, I started getting an error `Error: EBUSY: resource busy or locked: [path to favicon.svg here]` 

I can't reproduce it anywhere else than Powershell 7 and I'm not sure what's going on there.

I also explained this issue in detail here: https://github.com/lwojcik/eleventy-template-bliss/issues/91 

Any ideas?

**Comment by NJAldwin** [comment]
@lwojcik I don't really know where to start debugging this; however, #13 includes some image processing package updates, which might possibly resolve the underlying issue?

**Comment by gradyat** [comment]
I'm also on Windows and have the same issue. I had the issue a while back; coincidentally, I just tried to pick back up on it today, installed the new version and I get the same error. It works on a GitHub Codespace so seems it's specific to Windows.

**Comment by gradyat** [comment]
I found a strange workaround. Wrapping the shortcode in a Nunjucks if statement (one that is true and calls the shortcode) makes it build successfully with no error.

**Comment by lwojcik** [comment]
@gradyat thanks! Will have that in mind in case I see that problem again.

Tentatively closing this issue as the impact seems to be rather limited.
