### ISSUE TITLE
Add option for controlling apple icon padding

### ISSUE THREAD

**Issue by NVolcz** [NJAldwin/eleventy-plugin-gen-favicons#4]
I notice working on a website that this plugin produced out of proportion apple icons and found the recommendation from Evil Martians to add a 20px padding but I believe this is a general guideline. They don't follow this themself: https://evilmartians.com/apple-touch-icon.png
Would it be possible to add an option for controlling the amount of padding? From no padding to 20px for example.

**Comment by NJAldwin** [comment]
Sure, this should be pretty straightforward to add.
